-- MySQL Script generated by MySQL Workbench
-- Thu Jul 18 09:41:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codifica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codifica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codifica` DEFAULT CHARACTER SET utf8 ;
USE `codifica` ;

-- -----------------------------------------------------
-- Table `codifica`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`filmes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo_do_filme` VARCHAR(65) NULL,
  `titulo_original` VARCHAR(65) NULL,
  `ano_de_lancamento` INT(4) NULL,
  `classificacao` VARCHAR(45) NULL,
  `duracao` INT(3) NULL,
  `categorias` TEXT(255) NULL,
  `avaliacao` DECIMAL(3,1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `codifica` ;

-- -----------------------------------------------------
-- Placeholder table for view `codifica`.`ex-01`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`ex-01` (`titulo_original` INT, `avaliacao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codifica`.`ex-02`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`ex-02` (`id` INT, `titulo_do_filme` INT, `titulo_original` INT, `ano_de_lancamento` INT, `classificacao` INT, `duracao` INT, `categorias` INT, `avaliacao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codifica`.`ex-03`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`ex-03` (`titulo_do_filme` INT, `duracao` INT, `classificacao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codifica`.`ex-04`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`ex-04` (`id` INT, `titulo_do_filme` INT, `titulo_original` INT, `ano_de_lancamento` INT, `classificacao` INT, `duracao` INT, `categorias` INT, `avaliacao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codifica`.`ex-05`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`ex-05` (`id` INT, `titulo_do_filme` INT, `titulo_original` INT, `ano_de_lancamento` INT, `classificacao` INT, `duracao` INT, `categorias` INT, `avaliacao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codifica`.`ex-06`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`ex-06` (`COUNT(*)` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codifica`.`ex-07`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`ex-07` (`COUNT(*)` INT, `classificacao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `codifica`.`desafio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`desafio` (`registros` INT, `soma_duracao` INT, `notas` INT, `classificacao` INT);

-- -----------------------------------------------------
-- View `codifica`.`ex-01`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codifica`.`ex-01`;
USE `codifica`;
CREATE  OR REPLACE VIEW `ex-01` AS
SELECT titulo_original, avaliacao
FROM filmes
ORDER BY avaliacao DESC;

-- -----------------------------------------------------
-- View `codifica`.`ex-02`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codifica`.`ex-02`;
USE `codifica`;
CREATE  OR REPLACE VIEW `ex-02` AS
SELECT *
FROM filmes
ORDER BY duracao DESC
LIMIT 1;

-- -----------------------------------------------------
-- View `codifica`.`ex-03`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codifica`.`ex-03`;
USE `codifica`;
CREATE  OR REPLACE VIEW `ex-03` AS
SELECT titulo_do_filme, duracao, classificacao
FROM filmes
WHERE classificacao <= 16
ORDER BY duracao ASC
LIMIT 3;

-- -----------------------------------------------------
-- View `codifica`.`ex-04`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codifica`.`ex-04`;
USE `codifica`;
CREATE  OR REPLACE VIEW `ex-04` AS
SELECT * 
FROM filmes
ORDER BY ano_de_lancamento ASC, avaliacao DESC;

-- -----------------------------------------------------
-- View `codifica`.`ex-05`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codifica`.`ex-05`;
USE `codifica`;
CREATE  OR REPLACE VIEW `ex-05` AS
SELECT *
FROM filmes
WHERE categorias LIKE "%Drama%";

-- -----------------------------------------------------
-- View `codifica`.`ex-06`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codifica`.`ex-06`;
USE `codifica`;
CREATE  OR REPLACE VIEW `ex-06` AS
SELECT COUNT(*)
FROM filmes;

-- -----------------------------------------------------
-- View `codifica`.`ex-07`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codifica`.`ex-07`;
USE `codifica`;
CREATE  OR REPLACE VIEW `ex-07` AS
SELECT COUNT(*), classificacao
FROM filmes
GROUP BY classificacao;

-- -----------------------------------------------------
-- View `codifica`.`desafio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codifica`.`desafio`;
USE `codifica`;
CREATE  OR REPLACE VIEW `desafio` AS
SELECT COUNT(*) AS registros, SUM(duracao) AS soma_duracao, AVG(avaliacao) AS notas, classificacao
FROM filmes
GROUP BY classificacao;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `codifica`.`filmes`
-- -----------------------------------------------------
START TRANSACTION;
USE `codifica`;
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'Divertida Mente', 'Inside Out', 2015, 'Livre', 95, 'Animação, Aventura, Comédia', 8.1);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'Duna: Parte 2', 'Dune: Part Two', 2024, '14', 166, 'Ação, Aventura, Drana', 8.6);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'O Senhor dos Anéis: A Sociedade do Anel', 'The Lord of the Rings: The Fellowship of the Ring', 2001, '12', 178, 'Aventura, Fantasia', 8.8);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'O Poderoso Chefão', 'The Godfather', 1972, '16', 175, 'Crime, Drama', 9.2);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'Interestelar', 'Interstellar', 2014, '10', 169, 'Aventura, Drama, Sci-Fi', 8.6);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'Clube da Luta', 'Fight Club', 1999, '18', 139, 'Drama', 8.8);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'Matrix', 'The Matrix', 1999, '16', 136, 'Ação, Sci-Fi', 8.7);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'Cidade de Deus', 'City of God', 2002, '18', 130, 'Crime, Drama', 8.6);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'Parque dos Dinossauros', 'Jurassic Park', 1993, 'Livre', 127, 'Aventura, Sci-Fi', 8.1);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'O Iluminado', 'The Shining', 1980, '16', 146, 'Drama, Horror', 8.4);
INSERT INTO `codifica`.`filmes` (`id`, `titulo_do_filme`, `titulo_original`, `ano_de_lancamento`, `classificacao`, `duracao`, `categorias`, `avaliacao`) VALUES (DEFAULT, 'A Origem', 'Inception', 2010, '14', 148, 'Ação, Sci-Fi, Thriller', 8.8);

COMMIT;

