-- MySQL Script generated by MySQL Workbench
-- Wed Jul 17 19:57:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema codifica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codifica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codifica` DEFAULT CHARACTER SET utf8 ;
USE `codifica` ;

-- -----------------------------------------------------
-- Table `codifica`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codifica`.`filmes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo_do_filme` VARCHAR(65) NULL,
  `titulo_original` VARCHAR(65) NULL,
  `ano_de_lancamento` INT(4) NULL,
  `classificacao` VARCHAR(45) NULL,
  `duracao` INT(3) NULL,
  `categorias` TEXT(255) NULL,
  `avaliacao` DECIMAL(3,1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;